name: Homes
version: 1.0.0
author: Terpz710
api: [5.0.0]
main: Terpz710\Homes\Main
description: A Pocketmine-MP homes plugin.

permissions:
  homes.sethome:
    description: Allows players to set their home.
    default: true
  homes.home:
    description: Allows players to teleport to their home.
    default: true
  homes.delhome:
    description: Allows players to delete their home.
    default: true
  homes.homes:
    description: Allows players to list their available home locations.
    default: true
